### PR TITLE
12.15 planning service en model

### PR DESCRIPTION
**Pull request by rickvoermans**

### CODE REVIEW

**Review by nielss94 — APPROVED** [review]
Approooved

**Comment by rickvoermans** [comment]
[12.17 Form functionaliteit toevoegen aan personeelsleden](https://trello.com/c/EX0Kid7J/111-1217-form-functionaliteit-toevoegen-aan-personeelsleden)

**Comment by rickvoermans** [comment]
[12.16 PlanningModel maken](https://trello.com/c/oJ21BbFp/118-1216-planningmodel-maken)

**Comment by rickvoermans** [comment]
[12.16 PlanningModel maken](https://trello.com/c/oJ21BbFp/118-1216-planningmodel-maken)

**Comment by rickvoermans** [comment]
[12.15 PlanningService maken](https://trello.com/c/BWYjXNdK/117-1215-planningservice-maken)

**Pull request merged**
